name: nbdime-git-diff-action test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: nbdime-git-diff
      uses: raybellwaves/nbdime-git-diff-action@0.0.2
